M48
; DRILL file {KiCad 6.0.2+dfsg-1~bpo11+1} date Wed 04 May 2022 11:37:08 AM EDT
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-05-04T11:37:08-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.2+dfsg-1~bpo11+1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.500
%
G90
G05
T1
X116.4Y-43.4
X117.0Y-109.9
X146.9Y-82.0
T0
M30
